services:

    paloma_client.twig_profiler_extension:
        class: Paloma\ClientBundle\Twig\ProfilerExtension
        arguments:
            - '@Twig.loader'
            - '%kernel.root_dir%'
        public: false
        tags:
            - { name: twig.extension }

    paloma_client.paloma_profiler:
        class: Paloma\Shop\PalomaProfiler
        public: false

    paloma_client.paloma_data_collector:
        class: Paloma\Shop\PalomaDataCollector
        arguments:
            - '@paloma_client.paloma_profiler'
        public: false
        tags:
            - { name: data_collector, template: '@paloma_shop_client/profiler.html.twig', id: paloma }

    paloma_client.client_factory:
        class: Paloma\ClientBundle\Factory\ClientFactory
        arguments:
            - 'base_url injected'
            - 'api_key injected'
            - '@session'
            - 'shop_client_logger injected'
            - 'success_log_format injected'
            - 'error_log_format injected'
            - '@paloma_client.paloma_profiler'
            - 'cache_provider injected'

    paloma_client.default_client:
        class: Paloma\Shop\Paloma
        factory: 'paloma_client.client_factory:getDefaultClient'
